[package]
name = "nightcycle/instancify"
description = "Easily apply object properties, functions, and controls onto any in-game instance. Excellent for in-game prototyping as well as sending commands between objects."
version = "1.1.1"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
rx = "nightcycle/rx@3.7.3"
maid = "quenty/maid@2.0.1-canary"
signal = "quenty/signal@^2.0.0-canary"
